### ISSUE TITLE
[Feature] Refactor website to Gabsty v4

### ISSUE THREAD

**Issue by ISnackable** [ISnackable/isnackable.github.io#4]
**Todo**:

- [x] Use sanity.io
- [x] Framer Motion
- [ ] react-three-fiber
- [x] image lightbox

**Suggestion**: Change FB comment plugin to GitHub comment

- [x] Giscus (GitHub discussion)

**Tracking**: d31a1d77b3febd5c1be1bcc20bafee3d58698072 [feature-0-rewrite](/ISnackable/isnackable.github.io/tree/feature-0-rewrite) 

**Bug:**

- [ ] #11
